import type { PolicyArticle } from './types';

// Local demo data only. It is intentionally not a real-time policy source.
export const POLICY_LIBRARY: PolicyArticle[] = [
  { id: 'VAT001', title: '中华人民共和国增值税暂行条例', documentNumber: '国务院令第691号', issuer: '国务院', effectiveDate: '2017-11-19', status: 'review-required', articleNumber: '第一条、第四条', content: '条款摘要：在中华人民共和国境内销售货物、劳务、服务、无形资产或者不动产的单位和个人，应按规定缴纳增值税。', riskTypes: ['vat', 'revenue-consistency', 'three-flow'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'VAT002', title: '全面推开营业税改征增值税试点的通知', documentNumber: '财税〔2016〕36号', issuer: '财政部、国家税务总局', effectiveDate: '2016-05-01', status: 'review-required', articleNumber: '附件1 第二十七条', content: '条款摘要：纳税人取得的凭证用于规定项目的，其进项税额不得从销项税额中抵扣。', riskTypes: ['vat', 'invoice'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'CIT001', title: '中华人民共和国企业所得税法', documentNumber: '中华人民共和国主席令第63号', issuer: '全国人民代表大会常务委员会', effectiveDate: '2008-01-01', status: 'review-required', articleNumber: '第八条', content: '条款摘要：企业实际发生的与取得收入有关的、合理的支出，准予在计算应纳税所得额时扣除。', riskTypes: ['cit', 'industry', 'trend'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'CIT002', title: '企业所得税税前扣除凭证管理办法', documentNumber: '国家税务总局公告2018年第28号', issuer: '国家税务总局', effectiveDate: '2018-07-01', status: 'review-required', articleNumber: '第八条', content: '条款摘要：税前扣除凭证应当遵循真实性、合法性、关联性原则。', riskTypes: ['cit', 'invoice'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'INV001', title: '中华人民共和国发票管理办法', documentNumber: '国务院令第764号', issuer: '国务院', effectiveDate: '2023-07-20', status: 'review-required', articleNumber: '第二十一条', content: '条款摘要：不符合规定的发票，不得作为财务报销凭证，任何单位和个人有权拒收。', riskTypes: ['invoice'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'INV002', title: '中华人民共和国发票管理办法实施细则', documentNumber: '国家税务总局令第56号', issuer: '国家税务总局', effectiveDate: '2024-01-01', status: 'review-required', articleNumber: '第二十九条', content: '条款摘要：开具发票应当按照规定的时限、顺序、栏目，全部联次一次性如实开具。', riskTypes: ['invoice', 'revenue-consistency'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'REV001', title: '企业会计准则第14号——收入', documentNumber: '财会〔2017〕22号', issuer: '财政部', effectiveDate: '2018-01-01', status: 'review-required', articleNumber: '第五条', content: '条款摘要：企业应当在履行了合同中的履约义务，即客户取得相关商品控制权时确认收入。', riskTypes: ['revenue-consistency', 'trend', 'three-flow'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'COL001', title: '中华人民共和国税收征收管理法', documentNumber: '中华人民共和国主席令第49号', issuer: '全国人民代表大会常务委员会', effectiveDate: '2015-04-24', status: 'review-required', articleNumber: '第二十五条', content: '条款摘要：纳税人必须依照法律、行政法规规定或者税务机关依照法律、行政法规确定的申报期限、申报内容如实办理纳税申报。', riskTypes: ['revenue-consistency', 'three-flow'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'RND001', title: '关于进一步完善研发费用税前加计扣除政策的公告', documentNumber: '财政部 税务总局公告2023年第7号', issuer: '财政部、国家税务总局', effectiveDate: '2023-01-01', status: 'review-required', articleNumber: '第一条', content: '条款摘要：企业开展研发活动中实际发生的研发费用，未形成无形资产计入当期损益的，可按规定据实扣除并加计扣除。', riskTypes: ['benefit'], industries: ['software', 'trade', 'manufacturing', 'catering'] },
  { id: 'HTE001', title: '高新技术企业认定管理办法', documentNumber: '国科发火〔2016〕32号', issuer: '科技部、财政部、国家税务总局', effectiveDate: '2016-01-29', status: 'review-required', articleNumber: '第十一条', content: '条款摘要：认定为高新技术企业须同时满足核心自主知识产权、研发费用占比等规定条件。', riskTypes: ['benefit'], industries: ['software', 'trade', 'manufacturing'] },
];
